- name: Check if mysql is already installed
  shell: dpkg-query -l 'mariadb-server' 2> /dev/null || true
  changed_when: false
  register: dpkg_result

- name: Configure root password
  debconf:
    name: mariadb-server
    question: "{{ item }}"
    value: dummy
    vtype: password
  with_items:
    - mysql-server/root_password
    - mysql-server/root_password_again
  when: dpkg_result.stdout == ""
  changed_when: false

- name: Install package
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - mariadb-server
    - python-mysqldb

- name: Setup usermail user
  mysql_user:
    name: usermail
    host: localhost
    password: mailpassword
    state: present

- name: Setup servermail database
  mysql_db:
    name: servermail
    state: present
