- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - postfix
    - postfix-mysql

- name: Update configs
  template:
    src: "{{ item }}.j2"
    dest: "/etc/postfix/{{ item }}"
  with_items:
    - main.cf
    - virtual-alias-maps.cf
    - virtual-mailbox-domains.cf
    - virtual-mailbox-maps.cf
  register: postfix_main_config

- name: Restart service
  systemd:
    name: postfix
    state: restarted
  when: postfix_main_config.changed
