- name: Install package
  apt:
    name: rspamd
    state: present
    install_recommends: false
    update_cache: true

- name: Add configurations
  copy:
    src: "{{ item }}"
    dest: "/etc/rspamd/local.d/{{ item }}"
  with_items:
    - classifier-bayes.conf
    - milter_headers.conf
  register: rspamd_config

- name: Restart service
  systemd:
    name: rspamd
    state: restarted
  when: rspamd_config.changed
